// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwjxgtxekhtucwslxgeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3anhndHhla2h0dWN3c2x4Z2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDI2NDgsImV4cCI6MjA2Mjk3ODY0OH0.MJgGLsV_AE9Xmfpo0IxWOrdejRjMAoOw1LGJ4Flofv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);